import {
  BrainCircuit,
  ShieldCheck,
  AlertTriangle,
  BadgeCheck,
  ArrowRight,
  Shield,
  Lock,
  BellRing,
  Globe,
} from "lucide-react";

const recommendations = [
  {
    icon: Shield,
    title: "Block Suspicious URLs",
    description:
      "Immediately block detected phishing domains using DNS filtering, firewall rules, and Secure Web Gateway.",
    color: "text-red-400",
  },
  {
    icon: Lock,
    title: "Enable Multi-Factor Authentication",
    description:
      "Force MFA for all affected users to reduce credential theft and unauthorized account access.",
    color: "text-cyan-400",
  },
  {
    icon: BellRing,
    title: "Notify Security Operations Center",
    description:
      "Create a Priority-1 SOC incident and begin endpoint investigation across affected systems.",
    color: "text-yellow-400",
  },
  {
    icon: Globe,
    title: "User Awareness Campaign",
    description:
      "Warn employees not to interact with suspicious emails, fake login pages, or unknown attachments.",
    color: "text-green-400",
  },
];

function RecommendationCard() {
  return (
    <section className="rounded-[30px] border border-[#26324A] bg-[#101827]/85 p-7 shadow-2xl backdrop-blur-xl">

      {/* Header */}

      <div className="flex items-center justify-between">

        <div>

          <h2 className="text-2xl font-bold text-white">
            AI Recommendations
          </h2>

          <p className="mt-2 text-sm text-slate-400">
            Enterprise response generated by Gemini AI
          </p>

        </div>

        <div className="rounded-full bg-violet-500/10 px-4 py-2">

          <span className="text-sm font-medium text-violet-300">
            Gemini AI
          </span>

        </div>

      </div>

      {/* Priority */}

      <div className="mt-8 rounded-2xl border border-red-500/20 bg-red-500/10 p-5">

        <div className="flex items-center gap-3">

          <AlertTriangle
            size={22}
            className="text-red-400"
          />

          <div>

            <h3 className="font-semibold text-white">
              Incident Priority
            </h3>

            <p className="text-sm text-slate-400">
              Immediate response required
            </p>

          </div>

        </div>

        <h2 className="mt-4 text-4xl font-bold text-red-400">
          P1 - Critical
        </h2>

      </div>

      {/* AI Summary */}

      <div className="mt-6 rounded-2xl border border-cyan-500/20 bg-cyan-500/10 p-5">

        <div className="mb-3 flex items-center gap-3">

          <BrainCircuit
            size={22}
            className="text-cyan-400"
          />

          <h3 className="text-lg font-semibold text-white">
            Gemini AI Security Summary
          </h3>

        </div>

        <p className="text-sm leading-8 text-slate-300">

          Gemini AI identified multiple phishing indicators,
          credential harvesting techniques,
          fake login pages,
          suspicious branding,
          malicious URLs,
          and social engineering patterns.

          The uploaded image should be treated as a high-risk phishing
          campaign targeting enterprise users.

        </p>

      </div>

      {/* Recommendations */}

      <div className="mt-8 space-y-5">

        {recommendations.map((item, index) => {

          const Icon = item.icon;

          return (

            <div
              key={index}
              className="rounded-2xl border border-[#26324A] bg-[#162033] p-5 transition hover:border-cyan-500/30"
            >

              <div className="flex items-start gap-4">

                <div className="rounded-xl bg-[#0F172A] p-3">

                  <Icon
                    size={20}
                    className={item.color}
                  />

                </div>

                <div className="flex-1">

                  <h3 className="font-semibold text-white">
                    {item.title}
                  </h3>

                  <p className="mt-2 text-sm leading-7 text-slate-400">
                    {item.description}
                  </p>

                </div>

                <ArrowRight
                  size={20}
                  className="text-slate-500"
                />

              </div>

            </div>

          );

        })}

      </div>

      {/* Confidence */}

      <div className="mt-8 rounded-2xl border border-green-500/20 bg-green-500/10 p-5">

        <div className="flex items-center gap-3">

          <BadgeCheck
            size={22}
            className="text-green-400"
          />

          <div>

            <h3 className="text-lg font-semibold text-white">
              AI Confidence Score
            </h3>

            <p className="text-sm text-slate-400">
              Recommendation reliability
            </p>

          </div>

        </div>

        <h2 className="mt-4 text-4xl font-bold text-green-400">
          98.9%
        </h2>

      </div>

      {/* Final Verdict */}

      <div className="mt-6 rounded-2xl border border-cyan-500/20 bg-[#162033] p-5">

        <div className="flex items-center gap-3">

          <ShieldCheck
            size={22}
            className="text-cyan-400"
          />

          <div>

            <h3 className="text-lg font-semibold text-white">
              Enterprise Verdict
            </h3>

            <p className="text-sm text-slate-400">
              Final recommendation
            </p>

          </div>

        </div>

        <p className="mt-4 text-sm leading-8 text-slate-300">

          The uploaded image represents a likely phishing attempt with
          a very high confidence score.

          Enterprise security controls should immediately block the
          detected indicators, isolate affected endpoints, and notify
          the Security Operations Center (SOC) for further
          investigation.

        </p>

      </div>

    </section>
  );
}

export default RecommendationCard;